# Generated by Django 2.2.28 on 2025-03-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0002_play_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
