# Generated by Django 2.2.28 on 2025-03-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='releaseDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
