# Generated by Django 2.2.28 on 2025-03-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
