# Generated by Django 2.2.28 on 2025-03-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('playId', 'username')},
        ),
    ]
