# Generated by Django 5.1.7 on 2025-03-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plays", "0003_auto_20250310_1306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
