# Generated by Django 5.1.7 on 2025-03-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0005_alter_customuser_bio_alter_customuser_profilepicture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profilePicture',
            field=models.ImageField(default='default-profile-pic.jpg', upload_to='profile_images/'),
        ),
    ]
