# Generated by Django 5.1.7 on 2025-03-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0006_alter_customuser_bio_alter_customuser_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilePicture',
            field=models.ImageField(default='profile_images/default-profile-pic.jpg', upload_to='profile_images/'),
        ),
    ]
