# Generated by Django 5.1.7 on 2025-03-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0007_alter_customuser_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilePicture',
            field=models.ImageField(blank=True, default='profile_images/default-profile-pic.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
