# Generated by Django 2.2.28 on 2025-03-21 03:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0005_alter_customuser_bio_alter_customuser_profilepicture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profilePicture',
            field=models.ImageField(default='default-profile-pic.jpg', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
